Format scripts with shfmt

diff --git a/bin/ocr b/bin/ocr
--- a/bin/ocr
+++ b/bin/ocr
@@ -24,23 +24,23 @@ trap 'rm -f $tmpfile' EXIT HUP INT TRAP TERM
 # Check if the needed dependencies are installed
 dependencies=(tesseract maim notify-send xclip)
 for dependency in "${dependencies[@]}"; do
-    type -p "$dependency" &>/dev/null || {
-        # The reason why we are sending the error as a notification is because
-        # user is most likely going to run this script by binding it to their
-        # keyboard, therefor they cant see any text that is outputed using echo
-        notify-send "ocr" "Could not find '${dependency}', is it installed?"
-        echo "Could not find '${dependency}', is it installed?"
-        exit 1
-    }
+  type -p "$dependency" &>/dev/null || {
+    # The reason why we are sending the error as a notification is because
+    # user is most likely going to run this script by binding it to their
+    # keyboard, therefor they cant see any text that is outputed using echo
+    notify-send "ocr" "Could not find '${dependency}', is it installed?"
+    echo "Could not find '${dependency}', is it installed?"
+    exit 1
+  }
 done
 
 # Take screenshot by selecting the area
 maim --select --hidecursor --highlight --color=0.3,0.4,0.6,0.3 --bordersize=3 --format=png --quality=10 \
-    | mogrify -modulate 100,0 -resize 400% png:- \
-    | tesseract - - 2> /dev/null \
-    | sed 's/\x0c//' \
-    | tee "$tmpfile" \
-    | xclip -selection clip
+  | mogrify -modulate 100,0 -resize 400% png:- \
+  | tesseract - - 2>/dev/null \
+  | sed 's/\x0c//' \
+  | tee "$tmpfile" \
+  | xclip -selection clip
 
 # Send a notification with the text that was grabbed using OCR
 notify-send "Text extracted" -- "$(cat "$tmpfile")"
diff --git a/bin/pulseaudio_toggle_default_sink b/bin/pulseaudio_toggle_default_sink
--- a/bin/pulseaudio_toggle_default_sink
+++ b/bin/pulseaudio_toggle_default_sink
@@ -96,16 +96,16 @@ check_dependency() {
   local needed_programs=(pamixer pactl notify-send awk sed)
 
   for program in "${needed_programs[@]}"; do
-      if ! command -v "$program" >/dev/null 2>&1; then
-          all_needed_programs_installed=false
-          echo -n "Missing: "
-          text "$program"
-      fi
+    if ! command -v "$program" >/dev/null 2>&1; then
+      all_needed_programs_installed=false
+      echo -n "Missing: "
+      text "$program"
+    fi
   done
 
   if [ "$all_needed_programs_installed" = false ]; then
-      echo -e "\nPlease install the missing dependency"
-      exit 1
+    echo -e "\nPlease install the missing dependency"
+    exit 1
   fi
 }
 
@@ -132,7 +132,7 @@ swap_role_sink() {
   local role_to_change=$1
   while read -r name role sink input serial; do
     if [ "$role" = "$role_to_change" ]; then
-      while read -r index sink_name; do
+      while read -r index _sink_name; do
         if [ "$index" != "$sink" ]; then
           if is_pipewire; then
             pactl move-sink-input "$serial" "$index"
@@ -162,30 +162,30 @@ reset_inputs() {
 parse_options() {
   while (("$#")); do
     case "$1" in
-    -h | --help | help)
-      usage
-      ;;
-    -o | --output)
-      usage
-      ;;
-    media)
-      action=media
-      if [[ $# -ne 2 ]]; then
-        text "You need to specify a role"
-        echo
+      -h | --help | help)
         usage
-      fi
-      role=$2
-      shift 2
-      ;;
-    --) # end argument parsing
-      shift
-      break
-      ;;
-    *)
-      action=$1
-      shift
-      ;;
+        ;;
+      -o | --output)
+        usage
+        ;;
+      media)
+        action=media
+        if [[ $# -ne 2 ]]; then
+          text "You need to specify a role"
+          echo
+          usage
+        fi
+        role=$2
+        shift 2
+        ;;
+      --) # end argument parsing
+        shift
+        break
+        ;;
+      *)
+        action=$1
+        shift
+        ;;
     esac
   done
 }
diff --git a/bin/vol_bar b/bin/vol_bar
--- a/bin/vol_bar
+++ b/bin/vol_bar
@@ -25,49 +25,49 @@ icon_low=
 icon_high=
 
 progress() {
-    local percent=$1
-    local completed=$(( percent / 5 ))
-    local remaining=$(( 20 - completed ))
+  local percent=$1
+  local completed=$((percent / 5))
+  local remaining=$((20 - completed))
 
-    # pamixer --get-mute return true or false
-    # with a 0 exit code
-    if [ "$(pamixer --get-mute)" = true ]; then
-        icon=$icon_mute
+  # pamixer --get-mute return true or false
+  # with a 0 exit code
+  if [ "$(pamixer --get-mute)" = true ]; then
+    icon=$icon_mute
 
-    elif [ "$percent" -gt 50 ]; then
-        icon=$icon_high
+  elif [ "$percent" -gt 50 ]; then
+    icon=$icon_high
 
-    elif [ "$percent" -gt 0 ]; then
-        icon=$icon_low
+  elif [ "$percent" -gt 0 ]; then
+    icon=$icon_low
 
-    else
-        icon=$icon_off
-    fi
-    echo -ne "\n$icon "
-    if [ "$percent" -gt 0 ]; then
-        printf "%0.s█" $(seq $completed)
-    fi
-    [[ $remaining != 0 ]] && printf "%0.s " $(seq $remaining)
+  else
+    icon=$icon_off
+  fi
+  echo -ne "\n$icon "
+  if [ "$percent" -gt 0 ]; then
+    printf "%0.s█" $(seq $completed)
+  fi
+  [[ $remaining != 0 ]] && printf "%0.s " $(seq $remaining)
 }
 
 usage() {
-    echo "Usage: $0 up/down/mute [step]" >&2
-    echo "Example: $0 up 5" >&2
-    exit 1
+  echo "Usage: $0 up/down/mute [step]" >&2
+  echo "Example: $0 up 5" >&2
+  exit 1
 }
 
 case $action in
-    "up" )
-        pamixer --increase "$step" --sink @DEFAULT_SINK@
+  "up")
+    pamixer --increase "$step" --sink @DEFAULT_SINK@
     ;;
-    "down" )
-        pamixer --decrease "$step" --sink @DEFAULT_SINK@
+  "down")
+    pamixer --decrease "$step" --sink @DEFAULT_SINK@
     ;;
-    "mute" )
-        pamixer --toggle-mute --sink @DEFAULT_SINK@
+  "mute")
+    pamixer --toggle-mute --sink @DEFAULT_SINK@
     ;;
-    * )
-        usage
+  *)
+    usage
     ;;
 esac
 set +o errexit
