Add a dependency check

diff --git a/bin/pulseaudio_toggle_default_sink b/bin/pulseaudio_toggle_default_sink
--- a/bin/pulseaudio_toggle_default_sink
+++ b/bin/pulseaudio_toggle_default_sink
@@ -72,6 +72,7 @@ usage() {
   text "Usage:"
   echo -e "\t$0 [OPTION] [ACTION]"
   echo -e "\tToggle your defaut sound output or change your music player from an output to another"
+  echo -e "\tCompatible with pulseaudio and pipewire"
   echo
   text "Options"
   echo -e "\t-h, --help: Show help"
@@ -87,6 +88,25 @@ usage() {
   text "Roles"
   echo -e "\tOne of the strings video, music, game, event, phone, animation, production, a11y, test"
   exit
+}
+
+check_dependency() {
+  # Check basic dependency
+  local all_needed_programs_installed=true
+  local needed_programs=(pamixer pactl notify-send awk sed)
+
+  for program in "${needed_programs[@]}"; do
+      if ! command -v "$program" >/dev/null 2>&1; then
+          all_needed_programs_installed=false
+          echo -n "Missing: "
+          text "$program"
+      fi
+  done
+
+  if [ "$all_needed_programs_installed" = false ]; then
+      echo -e "\nPlease install the missing dependency"
+      exit 1
+  fi
 }
 
 sink_decription() {
@@ -190,6 +210,8 @@ is_pipewire() {
 main() {
 
   parse_options "$@"
+
+  check_dependency
 
   case "$action" in
     media) swap_role_sink "$role" ;;
