Rework script and change license to MIT for upstream

diff --git a/bin/rofi-rbw-filter-current-tab-domain b/bin/rofi-rbw-filter-current-tab-domain
--- a/bin/rofi-rbw-filter-current-tab-domain
+++ b/bin/rofi-rbw-filter-current-tab-domain
@@ -1,33 +1,56 @@
 #!/bin/bash
 #
-# Copyright (C) 2025 Julien Virey <julien.virey@gmail.com>
+# MIT License
 #
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, either version 3 of the License, or
-# (at your option) any later version.
+# Copyright (c) 2025 Julien Virey
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
+# Permission is hereby granted, free of charge, to any person obtaining a copy
+# of this software and associated documentation files (the "Software"), to deal
+# in the Software without restriction, including without limitation the rights
+# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+# copies of the Software, and to permit persons to whom the Software is
+# furnished to do so, subject to the following conditions:
 #
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <https://www.gnu.org/licenses/>.
+# The above copyright notice and this permission notice shall be included in all
+# copies or substantial portions of the Software.
 #
-#
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
+# SOFTWARE.
 
 set -o errexit -o pipefail -o nounset
 
 readonly focus_time=0.2
+
 # Detect if focused app is a browser
 is_browser() {
-  name="$(xprop -id "$(xdotool getwindowfocus)" WM_CLASS | cut -d'"' -f2 | tr '[:upper:]' '[:lower:]')"
+  name="$(xdotool getwindowfocus getwindowname | tr '[:upper:]' '[:lower:]')"
   [[ "$name" =~ chrome|firefox ]] && return 0
   return 1
 }
 
+init() {
+  # Check basic dependency
+  local all_needed_programs_installed=true needed_programs=(rofi-rbw xsel xdotool)
+  for program in "${needed_programs[@]}"; do
+    if ! command -v "$program" >/dev/null 2>&1; then
+      all_needed_programs_installed=false
+      echo "$program missing"
+    fi
+  done
+
+  if [ "$all_needed_programs_installed" = false ]; then
+    echo -e "\nPlease install the previous dependencies"
+    exit 1
+  fi
+}
+
 main() {
+  local parameters=()
   if is_browser; then
     sleep $focus_time
     xdotool key ctrl+l sleep "$focus_time"
@@ -38,13 +61,10 @@ main() {
     if [[ $current_clipboard == https://* ]]; then
       xsel --clipboard --clear
       domain=$(echo "$current_clipboard" | awk -F[/:] '{print $4}')
-      rofi-rbw --selector-args="-filter '${domain} '"
-    else
-      rofi-rbw
+      parameters+=(--selector-args="-filter '${domain} '")
     fi
-  else
-    rofi-rbw
   fi
+  rofi-rbw "${parameters[@]}"
 }
 
-main
+init && main
